@api=https://localhost:5000

################################# Identity API #################################

# @name Authenticate
POST {{api}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=client
&client_secret=secret
&username=admin
&password=admin@1234
&scope=order-management-api role


### Get All Customers
GET {{api}}/api/v1/customers
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get Customer By ID
GET {{api}}/api/v1/customers/0196aabc-eeff-7d71-bf42-e9c25f58ed8d
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Add Customer
POST {{api}}/api/v1/customers
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
  "firstName": "test1",
  "lastName": "test1",
  "email": "test1@test.com",
  "userId": "0196aabc-ee26-7bd7-a870-cc761ad67fca",
  "role": "User",
  "initialBalance": 80
}


### Add Order
POST {{api}}/api/v1/orders
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
  "customerId": "6b7a5de2-a1fa-4b76-9751-be9e455a7518",
  "items": [
    {
      "product": "biscuit",
      "unitPrice": 20,
      "quantity": 2
    }
  ]
}


### Get All Orders
GET {{api}}/api/v1/orders
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get order By ID
GET {{api}}/api/v1/orders/b6a970eb-ecfe-466c-8d18-0a8ba211e0ee
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Generate Invoice
POST {{api}}/api/v1/invoices/b6a970eb-ecfe-466c-8d18-0a8ba211e0ee
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
    "dueDate": "2025-05-07T18:00:00Z"
}


### Get All Invoices
GET {{api}}/api/v1/invoices
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get Invoice by ID
GET {{api}}/api/v1/invoices/713cc18b-124e-4e48-8836-215e436f4436
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Pay Invoice
POST {{api}}/api/v1/invoices/713cc18b-124e-4e48-8836-215e436f4436/pay
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}
