@api=https://localhost:5000

################################# Identity API #################################

# @name Authenticate
POST {{api}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=client
&client_secret=secret
&username=admin
&password=admin@1234
&scope=order-management-api role


### Get All Customers
GET {{api}}/api/v1/customers
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get Customer By ID
GET {{api}}/api/v1/customers/0196aad1-b18b-702b-83cb-12b6c4e8ba7f
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Add Customer
POST {{api}}/api/v1/customers
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
  "firstName": "test1",
  "lastName": "test1",
  "email": "test1@test.com",
  "userId": "0196aad1-b0b4-7e62-9b50-80c3ccf46e28",
  "role": "User",
  "initialBalance": 80
}


### Add Order
POST {{api}}/api/v1/orders
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
  "customerId": "0196aad1-b18b-702b-83cb-12b6c4e8ba7f",
  "items": [
    {
      "product": "biscuit",
      "unitPrice": 20,
      "quantity": 2
    }
  ]
}


### Get All Orders
GET {{api}}/api/v1/orders
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get order By ID
GET {{api}}/api/v1/orders/09d7e8ef-40dc-45b2-8025-8429fd814796
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Generate Invoice
POST {{api}}/api/v1/invoices/09d7e8ef-40dc-45b2-8025-8429fd814796
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}

{
    "dueDate": "2025-05-07T18:00:00Z"
}


### Get All Invoices
GET {{api}}/api/v1/invoices
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Get Invoice by ID
GET {{api}}/api/v1/invoices/e7f12878-849e-4401-87e3-bb9674346c84
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}


### Pay Invoice
POST {{api}}/api/v1/invoices/e7f12878-849e-4401-87e3-bb9674346c84/pay
Accept: application/json
Content-Type: application/json
authorization: bearer {{Authenticate.response.body.access_token}}
